# Generated by Django 2.2.2 on 2019-07-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20190626_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100)),
                ('uname', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('folder_name', models.CharField(max_length=200)),
            ],
        ),
    ]
