# Generated by Django 2.2.2 on 2019-07-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weibotask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiebaTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('folder_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='WeiboTask',
        ),
    ]
